openfire:
    build: .
    hostname: openfire
    domainname: comcloud.com
    ports:
        - "9090:9090"
        - "9091:9091"
        - "5222:5222"
        - "5223:5223"
        - "7070:7070"
        - "7777:7777"
        - "7443:7443"
        - "5229:5229"
        - "5269:5269"
